sudo: false

matrix:
  include:
    - language: python
      python: 3.8
      env:
        - PYTHONDONTWRITEBYTECODE=true
      before_script:
        - pip install codecov pytest pytest-cov black bandit
      script:
        - python3 -m black --check -q .
        - isort $(find . -name "*.py") -c
        - bandit -r . -x $(find . -name "test_*.py" | tr "\n" ",")
        - python3 -m pytest --cov-report=xml --cov . .
        - codecov --file coverage.xml
